2017/04/19 10:18:39  INFO [controller.(*Logic).Run](logic.go:45) server starting on[:6565]..
2017/04/19 10:20:53  INFO [controller.(*Logic).Run](logic.go:47) server starting on[:6565]..
2017/04/19 10:20:55 ERROR [models.CreateRobotAuthList](account.go:43) create robot auth list error: Error 1146: Table 'auth.robot_auth' doesn't exist
2017/04/19 10:21:25  INFO [controller.(*Logic).Run](logic.go:47) server starting on[:6565]..
2017/04/19 10:28:05  INFO [controller.(*Logic).Run](logic.go:47) server starting on[:6565]..
2017/04/19 10:30:47 ERROR [controller.(*Logic).CheckRobotAuth](srv_endpoint.go:90) update robot auth machine error: auth[fa962416-c2f1-4a1b-813b-b27960ad9b08] has bind machine
2017/04/19 10:33:58  INFO [controller.(*Logic).Run](logic.go:47) server starting on[:6565]..
2017/04/19 10:40:56  INFO [controller.(*Logic).Run](logic.go:47) server starting on[:6565]..
2017/04/19 10:41:37 ERROR [controller.(*Logic).CheckRobotAuth](srv_endpoint.go:97) check robot auth db auth_code[reechou-macbook] != req auth_code[reechou-macbok]
2017/04/19 16:57:05  INFO [controller.(*Logic).Run](logic.go:51) server starting on[:6565]..
2017/04/19 16:59:52  INFO [controller.(*Logic).Run](logic.go:51) server starting on[:6565]..
2017/04/19 17:00:46 DEBUG [models.GetRobotAuth](account.go:57) cannot find robot auth from auth[fa962416-c2f1-4a1b-813b-b27960ad9b08]
2017/04/19 17:01:59  INFO [controller.(*Logic).Run](logic.go:51) server starting on[:6565]..
2017/04/19 17:05:10  INFO [controller.(*Logic).Run](logic.go:51) server starting on[:6565]..
2017/04/19 17:08:46  INFO [controller.(*Logic).Run](logic.go:51) server starting on[:6565]..
2017/04/19 17:09:03 ERROR [controller.(*Logic).doCheckAuth](auth_logic.go:139) uri check error: B1i166Y6HF25zPcN B1i166Y6HF25zPcN or uri has used[1]
2017/04/19 17:09:55  INFO [controller.(*Logic).Run](logic.go:51) server starting on[:6565]..
2017/04/19 17:09:59 ERROR [controller.(*Logic).doCheckAuth](auth_logic.go:139) uri check error: B1i166Y6HF25zPcN B1i166Y6HF25zPcN or uri has used[1]
2017/04/19 17:13:31  INFO [controller.(*Logic).Run](logic.go:51) server starting on[:6565]..
2017/04/19 17:27:00  INFO [controller.(*Logic).Run](logic.go:51) server starting on[:6565]..
2017/04/19 17:27:07 ERROR [controller.(*Logic).doCheckAuth](auth_logic.go:150) uri check error: 8e88d4a0 583PTVoAgk1Vldi1 or uri has used[1]
2017/04/19 17:29:35  INFO [controller.(*Logic).Run](logic.go:51) server starting on[:6565]..
2017/04/19 17:30:42 ERROR [controller.(*Logic).doCheckAuth](auth_logic.go:150) uri check error: 66ff7d8f 66ff7d8f or uri has used[1]
